version: "3"
services:
  pyrog:
    build:
      context: .
    image: arkhn/pyrog:latest
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
    restart: "no"
    depends_on:
      - prisma
    volumes:
      - static:$WORKDIR/static
  prisma:
    image: prismagraphql/prisma:1.34
    restart: "no"
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres-db
            port: 5432
            user: prisma
            password: prisma
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres
    restart: "no"
    ports:
      - "9391:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
  static:
